version: "3"

services:
 files:
  image: nginx:1.23-alpine
  volumes:
   - ./conf/files.conf:/etc/nginx/conf.d/default.conf
   - /srv/public_html/:/usr/share/nginx/html/:ro
  networks:
   - frontend
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=files_frontend"
   - "traefik.http.routers.files.rule=PathPrefix(`/files/`)"
   - "traefik.http.routers.files.middlewares=files-prefix"
   - "traefik.http.middlewares.files-prefix.stripprefix.prefixes=/files"
   - "traefik.http.routers.files.entrypoints=websecure"
   - "de.wie-ei.autostart=true"


networks:
 frontend:
  external:
   name: traefik_frontend